/**
 * Types representing the structured calm daily blog generated by Gemini.
 */

export interface PositiveEvent {
  title: string;
  description: string;
}

export interface MindfulnessAdvice {
  title: string;
  content: string;
}

export interface CosmicForecast {
  planetaryStatus: string; // Factual celestial state, e.g. "Луна в фазе убывания, созвездие Скорпиона"
  humorousAdvice: string;  // Cozy, funny advice on what to do based on this
}

export interface CalmStory {
  title: string;
  story: string;     // Soothing real historical story, written in deep, rich, tranquil language
  source: string;    // Historical source citation
}

export interface FloraFaunaFact {
  subject: string;   // Creature or plant name
  fact: string;      // Captivating, peaceful, real fact
}

export interface HistoricFact {
  year: number;
  event: string;
}

export interface LiteraryQuote {
  author: string;
  text: string;
  bookOrYear?: string;
}

export interface CozyRecipe {
  name: string;
  description: string;
  ingredients: string[];
  steps: string[];
}

export interface DailyBlogData {
  dateString: string;          // E.g. "Суббота, 23 мая 2026"
  dayGreeting?: string;        // Calm, grounding invitation to notice oneself
  positiveEvents: PositiveEvent[];
  mindfulnessAdvice: MindfulnessAdvice[];
  cosmicForecast: CosmicForecast;
  calmStory: CalmStory;
  threeQuestions: string[];    // Array of exactly 3 introspection queries
  floraFaunaFact: FloraFaunaFact;
  historicFact: HistoricFact;
  literaryQuote: LiteraryQuote; // Custom comforting literature piece
  cozyRecipe: CozyRecipe;       // Cozy culinary recipe (herbal tea, milk infusions, etc.)
}

export interface UserDiaryEntry {
  date: string; // ISO date YYYY-MM-DD
  answers: string[]; // 3 answers
  createdAt: string;
}

export interface AudioTrack {
  id: string;
  name: string;
  active: boolean;
}
